### ISSUE TITLE
Module 'tensorflow' has not attribute 'atanh'

### ISSUE THREAD

**Issue by brakmic** [nicholastoddsmith/pythonml#4]
Hi,

I was following your article on [Price Predictions](https://nicholastsmith.wordpress.com/2017/11/13/cryptocurrency-price-prediction-using-deep-learning-in-tensorflow/) when this error happened. 

My conda / tensorflow version information:
```
tensorflow 1.2.1 py36_0
-----------------------
file name   : tensorflow-1.2.1-py36_0.tar.bz2
name        : tensorflow
version     : 1.2.1
build string: py36_0
build number: 0
channel     : https://repo.continuum.io/pkgs/free
size        : 21.0 MB
arch        : x86_64
constrains  : ()
date        : 2017-08-05
license     : Apache 2.0
license_family: Apache
md5         : 736b26f0b1b83caee9d260859c7d0714
platform    : win32
subdir      : win-64
url         : https://repo.continuum.io/pkgs/free/win-64/tensorflow-1.2.1-py36_0.tar.bz2
```

Maybe it's because tensorflow introduced some breaking changes recently?

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-d04f5a5c529e> in <module>()
      9 #Create the neural network in TensorFlow
     10 cnnr = ANNR(B[0].shape, ns, batchSize = 32, learnRate = 2e-5, 
---> 11             maxIter = 64, reg = 1e-5, tol = 1e-2, verbose = True)
     12 cnnr.fit(B, Y)

<ipython-input-9-0500b9780230> in __init__(self, _IS, _NA, batchSize, learnRate, loss, maxIter, name, optmzrn, pad, reg, tol, verbose, X, Y)
    211         with tf.variable_scope(self.name):
    212             self.TFVar = set(tf.global_variables())                 #All variables before model
--> 213             self.CreateModel()                                      #Populate TensorFlow graph
    214             self.TFVar = set(tf.global_variables()) - self.TFVar    #Only variables in this model
    215             self.Initialize()                                       #Start TF session and initialize vars

<ipython-input-9-0500b9780230> in CreateModel(self)
    221         if self.X is None:  #If no input variable was specified make a new placeholder
    222             self.X = tf.placeholder("float", [None] + self.IS)   #Input data matrix of samples
--> 223         self.O, self.W, self.B = _CreateANN(self.pad, self.NA, self.X)#Create graph; O is output from feedforward
    224         if self.Y is None:
    225             self.Y = tf.placeholder("float", self.O[-1].shape)     #Target matrix

<ipython-input-9-0500b9780230> in _CreateANN(PM, NA, X)
     55     for i, NAi in enumerate(NA):
     56         if NAi[0] == 'AF':      #Apply an activation function ('AF', 'name')
---> 57             AF = _GetActvFn(NAi[1])
     58             X = AF(X)
     59         elif NAi[0] == 'C':     #2-D Convolutional layer

<ipython-input-9-0500b9780230> in _GetActvFn(name)
    115     return: A handle for the tensorflow activation function
    116     '''
--> 117     return {'atanh': tf.atanh,          'elu': tf.nn.elu,
    118             'ident': tf.identity,
    119             'sig': tf.sigmoid,          'softplus': tf.nn.softplus,

AttributeError: module 'tensorflow' has no attribute 'atanh'

```

Kind regards,

**Comment by nicholastoddsmith** [comment]
Hi,

_atanh_ was introduced in 1.3.

Hope this helps,

N

**Comment by higherbeing** [comment]
HI brakmic ,
Are you able to figure out this issue? I am also getting the same issue

Thank you!

**Comment by brakmic** [comment]
Hi @higherbeing ,
Yes, after an update to 1.3 it worked without any problems.

Cheers,

**Comment by higherbeing** [comment]
I solved it by upgrading TF to 1.4.0

**Comment by balajiich** [comment]
But there is only 1.2.1 version of tensorflow in anaconda3.
